version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "cargo"
    directory: "/cms"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cms"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
