version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    labels:
      - "Dependencies"
      - "Front"

  - package-ecosystem: "cargo"
    directory: "/cms"
    schedule:
      interval: "weekly"
    labels:
      - "Dependencies"
      - "CMS"

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
    labels:
      - "Dependencies"
      - "API"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Dependencies"
      - "CI"
