-- EMAIL TOKEN (code 6 chiffres envoyé par mail)
DROP TABLE IF EXISTS EmailToken;
CREATE TABLE EmailToken(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	userId INTEGER NOT NULL,
	tokenHash CHAR(64) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	expiresAt TIMESTAMP NOT NULL,
	used INTEGER DEFAULT 0 NOT NULL,
	FOREIGN KEY(userId) REFERENCES User(id)
);

-- SESSION (token de session retourné après auth complète)
DROP TABLE IF EXISTS AuthSession;
CREATE TABLE AuthSession(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	userId INTEGER NOT NULL,
	tokenHash CHAR(64) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	expiresAt TIMESTAMP NOT NULL,
	revoked INTEGER DEFAULT 0 NOT NULL,
	FOREIGN KEY(userId) REFERENCES User(id)
);
