services:
  api:
    build: 
      context: .
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./uwu.db:/app/uwu.db
      - uploads:/var/www/uploads
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
          ignore:
            - uwu.db
            - README.md

volumes:
  uploads:
